import LayoutV3 from "@/components/templates/LayoutV3";

export default function SidebarV3() {
  return (
    <LayoutV3>
      <div className="flex flex-col">
        <h1 className="text-3xl font-bold mb-4">Welcome to the Dashboard</h1>
        <p className="text-lg text-justify">
          This is a simple page to demonstrate the layout with sidebar
          functionality.
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione deserunt architecto voluptatum sapiente? Reprehenderit perferendis itaque obcaecati pariatur praesentium expedita officia repellat porro, quis adipisci, illum totam modi reiciendis veniam accusamus? Earum aspernatur facere commodi tenetur a magni cupiditate eligendi ab laudantium? Omnis similique quia quod fuga molestiae architecto, tenetur fugit velit id cumque porro? Ullam provident doloremque magnam repellat, blanditiis quisquam praesentium. Dolorum aperiam aut exercitationem natus voluptatibus, ipsam totam nobis consequatur. Quis velit harum, temporibus perferendis animi omnis nam corrupti, sit impedit amet ipsam quos pariatur delectus iusto. Asperiores commodi natus vitae delectus? Molestias rem veritatis illum ullam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic reprehenderit asperiores maiores architecto, cumque distinctio temporibus aspernatur aliquam veritatis excepturi! Atque eveniet at quasi ea, molestias accusamus nam! Tenetur esse necessitatibus nisi provident ea qui natus officiis error! Totam expedita enim, odio maiores maxime illo perspiciatis rerum aliquid? Nemo, dolores sequi libero ducimus itaque quos labore magni, veritatis culpa magnam, asperiores quasi sunt deserunt reiciendis deleniti repudiandae. Atque necessitatibus voluptate maiores nobis quis quae sapiente repellendus optio eligendi alias tempora excepturi dolore cum delectus nam vero amet repudiandae adipisci consequuntur fugiat rem, id iste sequi commodi! Repudiandae quibusdam dolorem eaque numquam eveniet suscipit iste architecto blanditiis nemo voluptas, neque molestiae, veritatis ex dolorum libero consectetur dignissimos. Expedita, illum. Similique libero voluptatum obcaecati cumque architecto et nostrum nemo beatae modi aliquam quibusdam accusantium culpa autem distinctio dignissimos omnis neque cum quia, natus, corrupti blanditiis doloremque asperiores ad. Dolorum quo ullam, inventore sequi blanditiis fugit culpa quasi sit placeat nobis quas laudantium exercitationem iste! Architecto beatae, fugit itaque, quam ipsam facere reiciendis ullam, sit explicabo amet aut! Aliquam ex hic suscipit optio aperiam, unde molestiae quae, fugit perferendis nostrum ullam voluptatibus recusandae soluta accusantium autem in consectetur? Accusantium sequi officiis molestiae perspiciatis.
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione deserunt architecto voluptatum sapiente? Reprehenderit perferendis itaque obcaecati pariatur praesentium expedita officia repellat porro, quis adipisci, illum totam modi reiciendis veniam accusamus? Earum aspernatur facere commodi tenetur a magni cupiditate eligendi ab laudantium? Omnis similique quia quod fuga molestiae architecto, tenetur fugit velit id cumque porro? Ullam provident doloremque magnam repellat, blanditiis quisquam praesentium. Dolorum aperiam aut exercitationem natus voluptatibus, ipsam totam nobis consequatur. Quis velit harum, temporibus perferendis animi omnis nam corrupti, sit impedit amet ipsam quos pariatur delectus iusto. Asperiores commodi natus vitae delectus? Molestias rem veritatis illum ullam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic reprehenderit asperiores maiores architecto, cumque distinctio temporibus aspernatur aliquam veritatis excepturi! Atque eveniet at quasi ea, molestias accusamus nam! Tenetur esse necessitatibus nisi provident ea qui natus officiis error! Totam expedita enim, odio maiores maxime illo perspiciatis rerum aliquid? Nemo, dolores sequi libero ducimus itaque quos labore magni, veritatis culpa magnam, asperiores quasi sunt deserunt reiciendis deleniti repudiandae. Atque necessitatibus voluptate maiores nobis quis quae sapiente repellendus optio eligendi alias tempora excepturi dolore cum delectus nam vero amet repudiandae adipisci consequuntur fugiat rem, id iste sequi commodi! Repudiandae quibusdam dolorem eaque numquam eveniet suscipit iste architecto blanditiis nemo voluptas, neque molestiae, veritatis ex dolorum libero consectetur dignissimos. Expedita, illum. Similique libero voluptatum obcaecati cumque architecto et nostrum nemo beatae modi aliquam quibusdam accusantium culpa autem distinctio dignissimos omnis neque cum quia, natus, corrupti blanditiis doloremque asperiores ad. Dolorum quo ullam, inventore sequi blanditiis fugit culpa quasi sit placeat nobis quas laudantium exercitationem iste! Architecto beatae, fugit itaque, quam ipsam facere reiciendis ullam, sit explicabo amet aut! Aliquam ex hic suscipit optio aperiam, unde molestiae quae, fugit perferendis nostrum ullam voluptatibus recusandae soluta accusantium autem in consectetur? Accusantium sequi officiis molestiae perspiciatis.
        </p>
      </div>
    </LayoutV3>
  );
}
